;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	cua-copy-region
	cua-cut-region
	cua-paste
	cua-set-rectangle-mark
	electric-newline-and-maybe-indent
	indent-for-tab-command
	keyboard-escape-quit
	move-text-down
	move-text-up
	slime-autodoc-space
	slime-space
	))

(setq mc/cmds-to-run-once
      '(
	beginning-of-buffer
	compile
	mc/mark-next-lines
	pixel-scroll-precision
	project-compile
	slime-compile-defun
	slime-eval-defun
	))
